version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  clickhouse-server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  clickhouse-client:
    image: yandex/clickhouse-client
    volumes:
      - './init.sql:/init.sql'
    command: --host clickhouse-server --queries-file /init.sql
    depends_on:
      - "clickhouse-server"
#
#  kcat:
#    image: edenhill/kafkacat:1.7.0-PRE1
#    command: -b kafka:9092 -t mytopic -C